In [1]:
import pandas as pd
from pathlib import Path
import warnings

In [2]:
# Suppress potential future warnings from pandas
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- Configuration ---
# Use Path for OS compatibility. '../' goes up one level from the 'notebooks' folder to the project root.
PROJECT_ROOT = Path("..") 
ANALYTICS_DATA_DIR = PROJECT_ROOT / "data" / "analytics"

# --- Pick a file to inspect ---
file_to_check = "Albacete Municipio/Diario_Mes_demographics_analysis.parquet"
file_path = ANALYTICS_DATA_DIR / file_to_check

# --- Load the data ---
print(f"Loading data from: {file_path}")
df = pd.read_parquet(file_path)

# --- Inspect the DataFrame ---
print("\nShape (rows, columns):", df.shape)
print("\nColumns:", df.columns.to_list())

# Display the first 5 rows
df.head(20)

Loading data from: ..\data\analytics\Albacete Municipio\Diario_Mes_demographics_analysis.parquet

Shape (rows, columns): (810, 15)

Columns: ['mes', 'etiquetadelmes', 'origen', 'categoriadelvisitante', 'volumen_total', 'volumen_edad_18-24', 'volumen_edad_25-34', 'volumen_edad_35-44', 'volumen_edad_45-54', 'volumen_edad_55-64', 'volumen_edad_65 o más', 'volumen_edad_<18', 'volumen_genero_h', 'volumen_genero_m', 'volumen_genero_nr']

,mes,etiquetadelmes,origen,categoriadelvisitante,volumen_total,volumen_edad_18-24,volumen_edad_25-34,volumen_edad_35-44,volumen_edad_45-54,volumen_edad_55-64,volumen_edad_65 o más,volumen_edad_<18,volumen_genero_h,volumen_genero_m,volumen_genero_nr
0,202206,2022 junio,Extranjero,En tránsito,58808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,202206,2022 junio,Extranjero,Excursionista,6946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,202206,2022 junio,Extranjero,Excursionista recurrente,2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,202206,2022 junio,Extranjero,Habitualmente presente,1107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,202206,2022 junio,Extranjero,Habitualmente presente en tránsito,299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,202206,2022 junio,Extranjero,Residente,9647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,202206,2022 junio,Extranjero,Residente en tránsito,549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,202206,2022 junio,Extranjero,Turista,15959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,202206,2022 junio,Extranjero,Turista en tránsito,4768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,202206,2022 junio,Local,En tránsito,100928,4305.0,9989.0,15315.0,17213.0,13254.0,12890.0,14285.0,54239.0,33006.0,NaN
10,202206,2022 junio,Local,Excursionista,67455,2519.0,5814.0,9109.0,10840.0,9231.0,9785.0,8759.0,32061.0,23978.0,NaN
11,202206,2022 junio,Local,Excursionista recurrente,107092,4631.0,11699.0,18387.0,18080.0,14263.0,11895.0,16016.0,57139.0,37808.0,24.0
12,202206,2022 junio,Local,Habitualmente presente,79085,3927.0,7514.0,10713.0,13141.0,12151.0,12501.0,11926.0,40493.0,31338.0,42.0
13,202206,2022 junio,Local,Habitualmente presente en tránsito,6756,185.0,380.0,697.0,1103.0,810.0,570.0,351.0,2088.0,2008.0,NaN
14,202206,2022 junio,Local,Residente,3254137,197460.0,324715.0,490768.0,552516.0,438982.0,666906.0,563613.0,1770123.0,1464019.0,818.0
15,202206,2022 junio,Local,Residente en tránsito,62430,3066.0,6019.0,9223.0,11522.0,8332.0,10171.0,10096.0,33539.0,24890.0,NaN
16,202206,2022 junio,Local,Turista,26760,915.0,1950.0,2719.0,4236.0,3786.0,4008.0,3414.0,11808.0,9214.0,NaN
17,202206,2022 junio,Local,Turista en tránsito,1982,21.0,143.0,177.0,246.0,250.0,237.0,37.0,639.0,472.0,NaN
18,202206,2022 junio,NoLocal,En tránsito,1084558,34993.0,89809.0,146990.0,149784.0,117790.0,157006.0,133688.0,479347.0,350437.0,276.0
19,202206,2022 junio,NoLocal,Excursionista,217343,4913.0,15245.0,26794.0,27126.0,20359.0,24668.0,15291.0,78442.0,55872.0,82.0