In [1]:
import pandas as pd
from pathlib import Path
import warnings

In [2]:
# Suppress potential future warnings from pandas
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- Configuration ---
# Use Path for OS compatibility. '../' goes up one level from the 'notebooks' folder to the project root.
PROJECT_ROOT = Path("..") 
ANALYTICS_DATA_DIR = PROJECT_ROOT / "data" / "analytics"

# --- Pick a file to inspect ---
file_to_check = "CCAA Castilla-La Mancha/Llegada_origin_analysis.parquet"
file_path = ANALYTICS_DATA_DIR / file_to_check

# --- Load the data ---
print(f"Loading data from: {file_path}")
df = pd.read_parquet(file_path)

# --- Inspect the DataFrame ---
print("\nShape (rows, columns):", df.shape)
print("\nColumns:", df.columns.to_list())

# Display the first 5 rows
df.head(20)

Loading data from: ..\data\analytics\CCAA Castilla-La Mancha\Llegada_origin_analysis.parquet

Shape (rows, columns): (443572, 11)

Columns: ['fecha', 'origen', 'categoriadelvisitante', 'volumen_total', 'volumen_municipio', 'volumen_nacionalidad', 'origen_detalle', 'provincia_detalle', 'year', 'month', 'weekday']

,fecha,origen,categoriadelvisitante,volumen_total,volumen_municipio,volumen_nacionalidad,origen_detalle,provincia_detalle,year,month,weekday
0,2022-06-01,Extranjero,Habitualmente presente,272,NaN,20.0,Alemania,None,2022,6,Wednesday
1,2022-06-01,Extranjero,Habitualmente presente,272,NaN,23.0,Andorra,None,2022,6,Wednesday
2,2022-06-01,Extranjero,Habitualmente presente,272,NaN,32.0,Francia,None,2022,6,Wednesday
3,2022-06-01,Extranjero,Habitualmente presente,272,NaN,24.0,Países Bajos,None,2022,6,Wednesday
4,2022-06-01,Extranjero,Habitualmente presente,272,NaN,47.0,Portugal,None,2022,6,Wednesday
5,2022-06-01,Extranjero,Habitualmente presente,272,NaN,33.0,Rumania,None,2022,6,Wednesday
6,2022-06-01,Extranjero,Turista,6310,NaN,715.0,Alemania,None,2022,6,Wednesday
7,2022-06-01,Extranjero,Turista,6310,NaN,47.0,Andorra,None,2022,6,Wednesday
8,2022-06-01,Extranjero,Turista,6310,NaN,22.0,Argentina,None,2022,6,Wednesday
9,2022-06-01,Extranjero,Turista,6310,NaN,89.0,Austria,None,2022,6,Wednesday
10,2022-06-01,Extranjero,Turista,6310,NaN,120.0,Brasil,None,2022,6,Wednesday
11,2022-06-01,Extranjero,Turista,6310,NaN,33.0,Bulgaria,None,2022,6,Wednesday
12,2022-06-01,Extranjero,Turista,6310,NaN,351.0,Bélgica,None,2022,6,Wednesday
13,2022-06-01,Extranjero,Turista,6310,NaN,40.0,Canadá,None,2022,6,Wednesday
14,2022-06-01,Extranjero,Turista,6310,NaN,33.0,Chile,None,2022,6,Wednesday
15,2022-06-01,Extranjero,Turista,6310,NaN,21.0,China,None,2022,6,Wednesday
16,2022-06-01,Extranjero,Turista,6310,NaN,110.0,Colombia,None,2022,6,Wednesday
17,2022-06-01,Extranjero,Turista,6310,NaN,38.0,Croacia,None,2022,6,Wednesday
18,2022-06-01,Extranjero,Turista,6310,NaN,28.0,Dinamarca,None,2022,6,Wednesday
19,2022-06-01,Extranjero,Turista,6310,NaN,302.0,EE.UU,None,2022,6,Wednesday

In [3]:
unique_values = df['categoriadelvisitante'].unique()
print(unique_values)

['Habitualmente presente' 'Turista']

In [4]:
len(df)

443572